## Laboratorium 5 - algorytm Najbliższej Średniej (NM)


### Opis
Celem laboratorium jest implementacja klasyfikatora najbliższej średniej NM (*Nearest Mean*).


### Zadanie 1
* Wczytaj dane.
* Wszystkie poniższe zadania wykonaj dla wszystkich dostępnych klas i wszystkich cech.

In [51]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [52]:
with open('./dataset/dataset.npz', 'rb') as f:
    data = np.load(f)
    train, test = data['train'], data['test']

In [53]:
train_df = pd.DataFrame(train)
test_df = pd.DataFrame(test)

In [54]:
y_train = train_df[0]
y_test = test_df[0]
X_train = train_df.drop(columns=[0,1])
X_test = test_df.drop(columns=[0,1])

In [55]:
X_train.shape, y_train.shape

((2244, 14), (2244,))

In [56]:
X_train

,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.390930,1.102500,0.733510,0.720220,0.694740,0.179540,0.076072,1.053200,0.059213,0.157470,0.024197,0.009541,0.000247,1.204200
1,0.936710,2.415100,0.729800,0.817930,0.864910,0.334390,0.080539,1.180500,0.048722,0.120510,0.014314,0.003998,0.000372,1.308300
2,0.837500,1.951200,0.490500,0.968000,0.982460,0.651380,0.016224,0.047908,0.005119,0.035621,0.001267,0.000322,0.000011,0.235140
3,0.907550,2.582000,0.623940,0.968370,0.998250,0.556740,0.031714,0.183050,0.079387,0.162130,0.025613,0.007412,0.000699,1.695100
4,0.884850,2.239800,0.557540,0.979970,0.998250,0.679740,0.009129,0.015166,0.025658,0.087206,0.007548,0.002152,0.000179,0.751540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2239,0.985425,12.367959,0.965230,0.802650,0.975840,0.043345,0.196795,7.280538,0.013304,0.035287,0.002212,0.000395,0.000086,0.316025
2240,0.732868,2.193675,0.451017,0.895804,0.917298,0.656747,0.030173,0.147090,0.012712,0.048700,0.000179,0.000484,-0.000019,0.363004
2241,0.972539,2.580435,0.604563,0.943933,0.927550,0.412375,0.027216,0.261505,0.093553,0.169002,0.032028,0.010133,0.000466,2.262180
2242,0.869988,2.412292,0.474942,0.894748,1.136941,0.723794,0.003889,0.034966,0.113536,0.209715,0.040135,0.010886,0.001081,2.261769
2243,0.854293,2.719806,0.675552,0.979863,0.943090,0.494818,0.010955,-0.045633,0.113165,0.188330,0.037564,0.013313,0.000703,1.755229

In [57]:
# scaler = StandardScaler() # mean = 0, std = 1
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
# X_train = pd.DataFrame(X_train)
# X_test = pd.DataFrame(X_test)

### Zadanie 2
Zaimplementuj klasyfikator najbliższej średniej (NM) z zastosowaniem odległości Euklidesa i wykonaj klasyfikację. Wyświetl wynik klasyfikacji (accuracy).

In [58]:
classes = y_train.unique()
means = np.zeros((len(classes), X_train.shape[1])) # mean of each class for each feature
means.shape, classes

((30, 14),
 array([36.,  5., 29., 35., 32., 23., 25., 28., 13., 30., 22., 24.,  2.,
        11.,  6., 27.,  3., 14.,  9., 33., 12.,  4.,  8., 34., 31., 15.,
        10.,  7.,  1., 26.]))

In [59]:
for i, c in enumerate(classes):
    means[i] = X_train[y_train == c].mean(axis=0) # mean of each column (across all rows -> axis = 0)
means[:3]

array([[4.70290194e-01, 1.09348821e+00, 7.95978174e-01, 6.55385271e-01,
        5.19715549e-01, 1.27554036e-01, 1.02322465e-01, 1.96272979e+00,
        8.04657997e-02, 1.85363993e-01, 3.39414125e-02, 1.32033462e-02,
        3.84921834e-04, 1.43962360e+00],
       [8.82258596e-01, 1.93061219e+00, 6.43787864e-01, 8.41444822e-01,
        8.88338394e-01, 3.40911208e-01, 5.22937661e-02, 5.28065624e-01,
        5.46568826e-02, 1.35256871e-01, 1.86006869e-02, 6.42391965e-03,
        2.84375876e-04, 1.29854353e+00],
       [8.24198977e-01, 1.86740643e+00, 4.76534638e-01, 9.43865831e-01,
        1.00348805e+00, 6.40326641e-01, 2.88095347e-02, 1.63198888e-01,
        7.26880920e-03, 4.34453644e-02, 2.11981038e-03, 6.33760492e-04,
        1.79132870e-05, 2.87091352e-01]])

In [60]:
def edist(x,y):
    return np.sqrt(np.sum((x-y)**2))

In [61]:
means_df = pd.DataFrame(means)
def euclidean(X_test, means_df):
    y_pred = []

    for i, row in X_test.iterrows(): # for each test row
        dist = float('inf')
        closest_class = -1
        for im, rowm in means_df.iterrows(): # for the mean of each class
            edistance = edist(row, rowm) 
            if edistance < dist: # choose the closest mean across all features
                dist = edistance
                closest_class = classes[im] # each row in means are for the class in classes (row 0 -> class 36)
        y_pred.append(closest_class)
        
    return np.array(y_pred)
y_pred = euclidean(X_test, means_df)
y_pred.shape, y_test.shape

((1496,), (1496,))

In [62]:
accuracy = np.sum(y_pred == y_test) / len(y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.0254

### Zadanie 3
Zaimplementuj funkcję, która zwraca macierz kowariancji (*uwaga: biblioteka `numpy` posiada gotową implementację `cov` z którą powinieneś porównać swój wynik*).

\begin{equation*}
C = \frac{1}{n - 1} (X - \bar X)(X - \bar X)^T
\end{equation*}

gdzie:
* $X$ to macierz danych,
* $\bar X$ to wektor średnich wartości cech.

In [63]:
X_mean = X_train.mean(axis=0)
X_mean

2     0.727872
3     2.523966
4     0.507512
5     0.905648
6     0.946824
7     0.538768
8     0.037754
9     0.552833
10    0.051356
11    0.124603
12    0.017792
13    0.005992
14    0.000381
15    1.150512
dtype: float64

In [64]:
X_train.shape, X_mean.shape

((2244, 14), (14,))

In [65]:
def cov_matrix(X, X_mean):
    n = X.shape[0]
    X_centered = X - X_mean
    # transpose first matrix not the second one, because pandas and numpy have different default orientations than statistical definition
    return (X_centered.T @ X_centered) / (n-1)
my_cov = cov_matrix(X_train, X_mean)
my_cov.shape

(14, 14)

In [66]:
my_cov

,2,3,4,5,6,7,8,9,10,11,12,13,14,15
2,0.044131,0.312924,0.025835,0.005660,0.006950,-0.005770,-0.001067,-0.016312,-0.001618,-0.002101,-0.000511,-0.000146,-2.066121e-05,-0.029466
3,0.312924,7.980702,0.395358,-0.025983,0.013098,-0.321130,0.021397,0.739677,-0.030614,-0.046592,-0.010910,-0.003678,-2.837456e-04,-0.549524
4,0.025835,0.395358,0.041330,-0.009520,-0.008229,-0.033982,0.003888,0.104763,-0.001777,-0.002411,-0.000595,-0.000180,-2.390658e-05,-0.030416
5,0.005660,-0.025983,-0.009520,0.017389,0.009900,0.017828,-0.003781,-0.097412,0.000517,0.000629,0.000171,0.000042,8.853137e-06,0.007134
6,0.006950,0.013098,-0.008229,0.009900,0.017980,0.015112,-0.003237,-0.081844,0.000521,0.000673,0.000172,0.000045,7.754637e-06,0.007519
7,-0.005770,-0.321130,-0.033982,0.017828,0.015112,0.047761,-0.006408,-0.154722,0.001035,0.001385,0.000349,0.000106,1.579016e-05,0.016843
8,-0.001067,0.021397,0.003888,-0.003781,-0.003237,-0.006408,0.001624,0.043569,-0.000192,-0.000262,-0.000054,-0.000011,-2.892800e-06,-0.004047
9,-0.016312,0.739677,0.104763,-0.097412,-0.081844,-0.154722,0.043569,1.312227,-0.008216,-0.012089,-0.002799,-0.000841,-9.341332e-05,-0.152473
10,-0.001618,-0.030614,-0.001777,0.000517,0.000521,0.001035,-0.000192,-0.008216,0.001347,0.001825,0.000488,0.000161,1.279272e-05,0.020255
11,-0.002101,-0.046592,-0.002411,0.000629,0.000673,0.001385,-0.000262,-0.012089,0.001825,0.002874,0.000718,0.000258,1.504065e-05,0.026864
12,-0.000511,-0.010910,-0.000595,0.000171,0.000172,0.000349,-0.000054,-0.002799,0.000488,0.000718,0.000197,0.000071,3.954962e-06,0.006812
13,-0.000146,-0.003678,-0.000180,0.000042,0.000045,0.000106,-0.000011,-0.000841,0.000161,0.000258,0.000071,0.000028,1.001671e-06,0.002052
14,-0.000021,-0.000284,-0.000024,0.000009,0.000008,0.000016,-0.000003,-0.000093,0.000013,0.000015,0.000004,0.000001,1.857382e-07,0.000208
15,-0.029466,-0.549524,-0.030416,0.007134,0.007519,0.016843,-0.004047,-0.152473,0.020255,0.026864,0.006812,0.002052,2.075662e-04,0.362792

In [67]:
cov = np.cov(X_train.T)
cov_np = pd.DataFrame(cov)

In [68]:
is_equal = np.allclose(my_cov, cov_np, rtol=1e-5)
print(f"Matrices are equal: {is_equal}")

Matrices are equal: True

### Zadanie 4
Zaimplementuj klasyfikator najbliższej średniej (NM) z zastosowaniem odległości Mahalanobisa i wykonaj klasyfikację. Wyświetl wynik klasyfikacji (accuracy).

\begin{equation*}
D_j = \sqrt{ (x - \mu_j)^T S_j^{-1}(x - \mu_j) },
\end{equation*}

gdzie:
* $D_j$ to odległość klasyfikowanej próbki od klasy $j$, 
* $\mu_j$ to wektor średnich wartości cech dla klasy $j$, 
* $S_j^{-1}$ to macierz odwrotna do macierzy kowariancji klasy $j$, 
* a $x$ to klasyfikowana próbka.

> Podpowiedź: Do obliczenia macierzy odwrotnej możesz użyć funkcji `linalg.inv` z biblioteki `numpy`.

> UWAGA: W niniejszym zadaniu możesz zastosować dowolną strukturę kodu (nie musisz trzymać się struktury z poprzedniego zadania), jednak algorytm NM należy zaimplementować samodzielnie – bez użycia gotowych rozwiązań (np. z biblioteki `scikit-learn`).

<span style="text-decoration:underline">Referencje</span>

1. Mahalanobis, P C, _On test and measures of group divergence : theoretical formulae_, Journal and Proceedings of Asiatic Society of Bengal (New Series) Vol. 26, pp. 541-588. 1930. (URL: http://library.isical.ac.in:8080/xmlui/bitstream/handle/10263/1639/029.pdf)
2. McLachlan, Goeffrey J. _Mahalanobis distance_, Resonance, pp. 20-26. 1999. (URL: https://www.ias.ac.in/article/fulltext/reso/004/06/0020-0026)

In [69]:
class_cov_matrices = {}

for c in classes:
    each_class = X_train[y_train == c]
    
    class_mean = each_class.mean(axis=0)
    
    cov_m = cov_matrix(each_class, class_mean)
    
    class_cov_matrices[c] = cov_m

In [70]:
class_cov_matrices[36].shape

(14, 14)

In [71]:
def mdist(x, u, S): # x, u -> (14,)
    x = np.array(x)
    u = np.array(u)
    
    x_ = np.array(x - u) # numpy can treat it as a row vector (1,14)
    
    # (1,14) @ (14, 14) -> (1,14) @ (14, 1) -> 1
    return np.sqrt( x_ @ np.linalg.inv(S) @ x_.T )

In [72]:
def mahalanobis(X_test, means_df):
    y_pred_maha = []

    for _, row in X_test.iterrows():
        dist = float('inf')
        closest_class = -1
        
        for im, rowm in means_df.iterrows():
            c = classes[im]
            S = class_cov_matrices[c]
            mdistance = mdist(row, rowm, S) 
            
            if mdistance < dist:
                dist = mdistance
                closest_class = c
                
        y_pred_maha.append(closest_class)
        
    return np.array(y_pred_maha)
    

y_pred_maha = mahalanobis(X_test, means_df)
y_pred_maha.shape, y_test.shape

((1496,), (1496,))

In [73]:
accuracy_m = np.sum(y_pred_maha == y_test) / len(y_test)
print(f"Accuracy: {accuracy_m:.4f}")

Accuracy: 0.5635

Without scaling the data

In [75]:
y_pred_e = euclidean(X_test, means_df)
y_pred_m = mahalanobis(X_test, means_df)

acc_e = np.sum(y_pred_e == y_test) / len(y_test)
acc_m = np.sum(y_pred_m == y_test) / len(y_test)

print(f"Euclidean accuracy: {acc_e:.4f}")
print(f"Mahalanobis accuracy: {acc_m:.4f}")

Euclidean accuracy: 0.0254
Mahalanobis accuracy: 0.5635

With scaled data

In [78]:
scaler = StandardScaler() # mean = 0, std = 1
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

for i, c in enumerate(classes):
    means[i] = X_train[y_train == c].mean(axis=0) # mean of each column (across all rows -> axis = 0)

means_df = pd.DataFrame(means)

In [79]:
y_pred_e = euclidean(X_test, means_df)
y_pred_m = mahalanobis(X_test, means_df)

acc_e = np.sum(y_pred_e == y_test) / len(y_test)
acc_m = np.sum(y_pred_m == y_test) / len(y_test)

print(f"Euclidean accuracy: {acc_e:.4f}")
print(f"Mahalanobis accuracy: {acc_m:.4f}")

Euclidean accuracy: 0.5762
Mahalanobis accuracy: 0.1176

Why accuracy decreased in using mahalanobis distance and increased in euclidean?

* Euclidean distance treats all dimensions equally, so standardization helps it by putting everything on the same scale

* Mahalanobis inherently normalizes data through the covariance matrix, therefore scaling destroys valuable information about the different variances between classes

* Some class covariance matrices might become close to singular after standardization